export type GoalStatus =
  | 'queued'
  | 'running'
  | 'waiting_human'
  | 'paused'
  | 'completed'
  | 'failed'
  | 'cancelled'

export interface GoalRun {
  id: string
  name: string
  sessionId: string
  description: string
  status: GoalStatus
  iter: number
  maxIter: number
  tokens: number
  tokenBudget: number
  duration: string
  maxDuration: number
  sandbox: 'lap' | 'local'
  createdAt: string
  activity: string
  question?: string
  pr?: string
  distillPrs?: string[]
  error?: string
}

export const STATUS_LABEL: Record<GoalStatus, string> = {
  queued: '队列中',
  running: '运行中',
  waiting_human: '等待回复',
  paused: '已暂停',
  completed: '已完成',
  failed: '已失败',
  cancelled: '已取消',
}

export const STATUS_ORDER: GoalStatus[] = [
  'queued',
  'running',
  'waiting_human',
  'paused',
  'completed',
  'failed',
  'cancelled',
]

export const BOARD_COLUMNS: { status: GoalStatus; label: string }[] = [
  { status: 'queued', label: '队列中' },
  { status: 'running', label: '运行中' },
  { status: 'waiting_human', label: '等待回复' },
  { status: 'paused', label: '已暂停' },
  { status: 'completed', label: '已完成' },
  { status: 'failed', label: '失败' },
  { status: 'cancelled', label: '已取消' },
]

/** 合法的状态迁移 */
export const VALID_TRANSITIONS: Record<GoalStatus, GoalStatus[]> = {
  queued: ['running', 'cancelled'],
  running: ['waiting_human', 'paused', 'completed', 'failed'],
  waiting_human: ['running', 'paused', 'cancelled'],
  paused: ['running', 'cancelled'],
  completed: [],
  failed: ['queued'],
  cancelled: ['queued'],
}

export const MOCK_RUNS: GoalRun[] = [
  // ── queued ──
  {
    id: 'L045',
    name: 'add-export-csv',
    sessionId: 'export-csv-20260613',
    description: '订单列表页加 CSV 导出按钮',
    status: 'queued',
    iter: 0,
    maxIter: 30,
    tokens: 0,
    tokenBudget: 200000,
    duration: '-',
    maxDuration: 30,
    sandbox: 'lap',
    createdAt: '2026-06-13T12:00:00',
    activity: '等待可用 pod...',
  },
  {
    id: 'L046',
    name: 'add-rate-limit',
    sessionId: 'rate-limit-20260613',
    description: 'API 网关加全局限流中间件，支持 IP + token 双维度',
    status: 'queued',
    iter: 0,
    maxIter: 40,
    tokens: 0,
    tokenBudget: 350000,
    duration: '-',
    maxDuration: 45,
    sandbox: 'lap',
    createdAt: '2026-06-13T12:00:00',
    activity: '等待可用 pod...',
  },
  {
    id: 'L047',
    name: 'migrate-to-ts5',
    sessionId: '',
    description: '全项目 TypeScript 4.x → 5.x 升级，修复所有 breaking changes',
    status: 'queued',
    iter: 0,
    maxIter: 60,
    tokens: 0,
    tokenBudget: 800000,
    duration: '-',
    maxDuration: 90,
    sandbox: 'local',
    createdAt: '2026-06-13T12:00:00',
    activity: '队列中，等待调度...',
  },

  // ── running ──
  {
    id: 'L042',
    name: 'add-phone-field',
    sessionId: 'add-phone-field-20260613',
    description: '给 user 表加 phone 字段，含迁移、API、前端表单，全部测试通过',
    status: 'running',
    iter: 35,
    maxIter: 50,
    tokens: 280000,
    tokenBudget: 500000,
    duration: '22min',
    maxDuration: 60,
    sandbox: 'lap',
    createdAt: '2026-06-13T12:00:00',
    activity: '正在编写 API 集成测试...',
  },
  {
    id: 'L048',
    name: 'refactor-auth-middleware',
    sessionId: 'refactor-auth-20260613',
    description: 'JWT 认证中间件重构：抽取 verify/refresh 逻辑为独立 service',
    status: 'running',
    iter: 18,
    maxIter: 40,
    tokens: 150000,
    tokenBudget: 400000,
    duration: '10min',
    maxDuration: 50,
    sandbox: 'lap',
    createdAt: '2026-06-13T12:00:00',
    activity: '正在重构 TokenService...',
  },
  {
    id: 'L049',
    name: 'add-db-indexes',
    sessionId: 'db-indexes-20260613',
    description: '根据慢查询日志添加缺失的数据库索引，覆盖 orders/users/sessions 表',
    status: 'running',
    iter: 8,
    maxIter: 20,
    tokens: 45000,
    tokenBudget: 150000,
    duration: '3min',
    maxDuration: 20,
    sandbox: 'lap',
    createdAt: '2026-06-13T12:00:00',
    activity: '分析 EXPLAIN 输出，生成迁移...',
  },

  // ── waiting_human ──
  {
    id: 'L043',
    name: 'refactor-checkout',
    sessionId: 'refactor-checkout-20260613',
    description: '重构 checkout 流程，拆分 OrderService',
    status: 'waiting_human',
    iter: 12,
    maxIter: 50,
    tokens: 95000,
    tokenBudget: 300000,
    duration: '8min',
    maxDuration: 45,
    sandbox: 'lap',
    createdAt: '2026-06-13T12:00:00',
    activity: '等待 PM 回复...',
    question: 'redis 缓存还是 in-memory？当前并发量不高但未来可能扩展',
  },
  {
    id: 'L050',
    name: 'design-approval-flow',
    sessionId: 'approval-flow-20260613',
    description: '请假审批流：需要确认二级审批还是三级审批',
    status: 'waiting_human',
    iter: 6,
    maxIter: 30,
    tokens: 42000,
    tokenBudget: 200000,
    duration: '3min',
    maxDuration: 30,
    sandbox: 'local',
    createdAt: '2026-06-13T12:00:00',
    activity: '等待产品决策...',
    question: '审批流用二级（主管→HRBP）还是三级（主管→经理→HRBP）？',
  },

  // ── paused ──
  {
    id: 'L044',
    name: 'fix-issue-5',
    sessionId: '',
    description: '修复 issue #5: 订单金额计算精度丢失',
    status: 'paused',
    iter: 12,
    maxIter: 50,
    tokens: 78000,
    tokenBudget: 200000,
    duration: '5min',
    maxDuration: 30,
    sandbox: 'local',
    createdAt: '2026-06-13T12:00:00',
    activity: '已暂停',
  },
  {
    id: 'L051',
    name: 'upgrade-deps',
    sessionId: '',
    description: '批量升级 npm 依赖，处理 breaking changes',
    status: 'paused',
    iter: 22,
    maxIter: 40,
    tokens: 160000,
    tokenBudget: 300000,
    duration: '12min',
    maxDuration: 45,
    sandbox: 'lap',
    createdAt: '2026-06-13T12:00:00',
    activity: '等待依赖安全审计结果...',
  },
  {
    id: 'L052',
    name: 'add-e2e-dashboard',
    sessionId: '',
    description: '为 Dashboard 页补充 Playwright e2e 用例',
    status: 'paused',
    iter: 5,
    maxIter: 25,
    tokens: 30000,
    tokenBudget: 180000,
    duration: '2min',
    maxDuration: 25,
    sandbox: 'local',
    createdAt: '2026-06-13T12:00:00',
    activity: '开发环境 Playwright 端口冲突，等待修复...',
  },

  // ── completed ──
  {
    id: 'L038',
    name: 'add-payment',
    sessionId: 'add-payment-20260613',
    description: '集成 Stripe 支付',
    status: 'completed',
    iter: 48,
    maxIter: 50,
    tokens: 450000,
    tokenBudget: 500000,
    duration: '45min',
    maxDuration: 60,
    sandbox: 'lap',
    createdAt: '2026-06-13T12:00:00',
    activity: '执行成功',
    pr: 'conduit#128',
    distillPrs: ['skill#15'],
  },
  {
    id: 'L036',
    name: 'add-dark-mode',
    sessionId: 'dark-mode-20260613',
    description: '全局暗色模式切换，CSS 变量方案',
    status: 'completed',
    iter: 42,
    maxIter: 60,
    tokens: 380000,
    tokenBudget: 600000,
    duration: '38min',
    maxDuration: 75,
    sandbox: 'lap',
    createdAt: '2026-06-13T12:00:00',
    activity: '执行成功',
    pr: 'conduit#117',
    distillPrs: ['skill#12'],
  },
  {
    id: 'L035',
    name: 'fix-pagination-bug',
    sessionId: '',
    description: '列表分页 offset 计算错误，第3页后数据重复',
    status: 'completed',
    iter: 15,
    maxIter: 20,
    tokens: 85000,
    tokenBudget: 150000,
    duration: '8min',
    maxDuration: 20,
    sandbox: 'local',
    createdAt: '2026-06-13T12:00:00',
    activity: '执行成功',
    pr: 'conduit#115',
  },

  // ── failed ──
  {
    id: 'L040',
    name: 'fix-bug-2',
    sessionId: '',
    description: '修复首页加载缓慢问题',
    status: 'failed',
    iter: 30,
    maxIter: 50,
    tokens: 550000,
    tokenBudget: 500000,
    duration: '35min',
    maxDuration: 60,
    sandbox: 'lap',
    createdAt: '2026-06-13T12:00:00',
    activity: '执行失败',
    error: '超出 token 预算 (550K/500K)',
  },
  {
    id: 'L053',
    name: 'add-graphql-layer',
    sessionId: '',
    description: '在 REST 之上加 GraphQL 适配层，使用 Apollo Server',
    status: 'failed',
    iter: 18,
    maxIter: 45,
    tokens: 380000,
    tokenBudget: 400000,
    duration: '28min',
    maxDuration: 55,
    sandbox: 'lap',
    createdAt: '2026-06-13T12:00:00',
    activity: '执行失败',
    error: 'Schema 拼接阶段报错：N+1 查询问题无法自动解决',
  },
  {
    id: 'L054',
    name: 'migrate-session-store',
    sessionId: '',
    description: 'Session 存储从文件迁移到 Redis，保持向后兼容',
    status: 'failed',
    iter: 25,
    maxIter: 35,
    tokens: 420000,
    tokenBudget: 350000,
    duration: '22min',
    maxDuration: 40,
    sandbox: 'local',
    createdAt: '2026-06-13T12:00:00',
    activity: '执行失败',
    error: 'Redis 连接池在压测下耗尽，需切换到 ioredis 并调整 pool 配置',
  },

  // ── cancelled ──
  {
    id: 'L041',
    name: 'add-legacy-soap',
    sessionId: '',
    description: '对接老系统 SOAP 接口——需求取消，改用 REST',
    status: 'cancelled',
    iter: 3,
    maxIter: 30,
    tokens: 12000,
    tokenBudget: 200000,
    duration: '1min',
    maxDuration: 30,
    sandbox: 'local',
    createdAt: '2026-06-13T12:00:00',
    activity: '已取消',
  },
  {
    id: 'L055',
    name: 'add-feature-toggle',
    sessionId: '',
    description: '自建 feature flag 系统——决定改用 GrowthBook SaaS',
    status: 'cancelled',
    iter: 0,
    maxIter: 40,
    tokens: 0,
    tokenBudget: 300000,
    duration: '-',
    maxDuration: 40,
    sandbox: 'lap',
    createdAt: '2026-06-13T12:00:00',
    activity: 'Product 决定采购外部方案',
  },
]
